[project]
name = "pyadio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "takumi-nishimura", email = "clp13218@nitech.jp" }
]
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.10.4",
    "pyserial>=3.5",
]

[project.scripts]
pyadio = "pyadio:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pgliveapp>=0.1.0",
    "pytest>=8.3.4",
]
